### ISSUE TITLE
Fail to install CIMLR in R 4.2

### ISSUE THREAD

**Issue by JamesWu7** [danro9685/CIMLR#2]
Sorry to bother u, I encounter some issues when I install CIMLR. Thank u in advance!
The information is as following:

ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lquadmath
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [CIMLR.so] Error 1
ERROR: compilation failed for package ‘CIMLR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/CIMLR’
Downloading GitHub repo danro9685/CIMLR@R
Skipping CIMLR, it is already being installed

**Comment by danro9685** [comment]
Dear @jamesbangbang1126,

This is a compiler problem. You can google the error and find out how to fix it, as a start have a look here: https://thecoatlessprofessor.com/programming/cpp/rcpp-rcpparmadillo-and-os-x-mavericks-lgfortran-and-lquadmath-error/

I have just tested it and CIMLR installation works fine, once the compiler is fixed.

All the best,
Daniele

**Comment by JamesWu7** [comment]
Thank u so much.
