### ISSUE TITLE
Fail to install CIMLR in R4.3.1 in Windows

### ISSUE THREAD

**Issue by YihengJiang0912** [danro9685/CIMLR#3]
Hello dear authors, I kept getting error when installing CIMLR in R4.3.1 in Windows. I would be very grateful if you could give me some favor about this. 

Below is the error information:

library("devtools")
> install_github("danro9685/CIMLR", ref = 'R')
Using github PAT from envvar GITHUB_TOKEN
Downloading GitHub repo danro9685/CIMLR@R
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\59307\AppData\Local\Temp\Rtmp00R5rk\remotesb9406dcb539c\danro9685-CIMLR-d14531e/DESCRIPTION' (1.1s)
─  preparing 'CIMLR':
✔  checking DESCRIPTION meta-information ... 
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building 'CIMLR_1.0.0.tar.gz'
...
Error: package or namespace load failed for 'CIMLR' in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'D:/R-4.3.1/library/00LOCK-CIMLR/00new/CIMLR/libs/x64/CIMLR.dll':

Error: loading failed
Execution halted
ERROR: loading failed
* removing 'D:/R-4.3.1/library/CIMLR'

**Comment by danro9685** [comment]
Dear @YihengJiang0912,
I have just tested the installation on my Mac with the same R version and I worked, it seems a problem specific for your architecture.
Try to follow the advice on these forums:
https://stackoverflow.com/questions/52150491/error-in-indlx-as-logicallocal-as-logicalnow-unable-to-load-share
https://discourse.mc-stan.org/t/error-in-indl-x-as-logical-local-as-logical-now-windows-10/21902
All the best,
Daniele
